# Generated by Django 3.2 on 2025-04-06 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('screenplays', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='screenplay',
            options={'ordering': ['-created'], 'verbose_name': 'Screenplay', 'verbose_name_plural': 'Screenplays'},
        ),
        migrations.AlterField(
            model_name='character',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who created or uploaded the character.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.TextField(blank=True, help_text="A short description of the character's role or personality.", null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(help_text="Full name of the character (e.g., 'Alice', 'Captain Nemo').", max_length=128),
        ),
        migrations.AlterField(
            model_name='character',
            name='profile',
            field=models.TextField(blank=True, help_text='Detailed character profile including traits, backstory, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='screenplay',
            field=models.ForeignKey(help_text='The screenplay this character belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='screenplays.screenplay'),
        ),
        migrations.AlterField(
            model_name='screenplay',
            name='content',
            field=models.TextField(blank=True, help_text='The full text content of the screenplay.', null=True),
        ),
        migrations.AlterField(
            model_name='screenplay',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who created or uploaded the screenplay.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenplays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='screenplay',
            name='title',
            field=models.CharField(help_text='The title of the screenplay.', max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='character',
            unique_together={('name', 'screenplay')},
        ),
        migrations.AlterUniqueTogether(
            name='screenplay',
            unique_together={('title', 'created_by')},
        ),
    ]
