# Generated by Django 3.2 on 2025-04-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenplays', '0003_auto_20250410_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='names',
            field=models.CharField(blank=True, help_text='All names or nicknames mentioned in the story', max_length=512, null=True),
        ),
    ]
