# Generated by Django 3.2 on 2025-04-17 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screenplays', '0004_character_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneHighlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified.', verbose_name='modified at')),
                ('deleted', models.BooleanField(default=False, help_text='Set to False when an element is deleted')),
                ('name', models.CharField(help_text='Which check flagged this highlight.', max_length=64)),
                ('description', models.TextField(help_text='Why this scene was flagged.')),
                ('related_text', models.TextField(help_text='The snippet of the screenplay this refers to.')),
                ('screenplay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='screenplays.screenplay')),
            ],
            options={
                'ordering': ['screenplay', 'name'],
            },
        ),
    ]
