# Generated by Django 3.2 on 2025-04-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenplays', '0005_scenehighlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenehighlight',
            name='type',
            field=models.CharField(default='', help_text='Type of Check', max_length=64),
        ),
    ]
