# Generated by Django 3.2 on 2025-04-17 23:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screenplays', '0006_scenehighlight_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenplay',
            name='content_2',
            field=ckeditor.fields.RichTextField(blank=True, help_text='The full text content of the screenplay.', null=True),
        ),
    ]
