# Generated by Django 3.2 on 2025-04-18 09:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screenplays', '0008_alter_screenplay_content_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenplay',
            name='content_2',
        ),
        migrations.AlterField(
            model_name='screenplay',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='The full text content of the screenplay.', null=True),
        ),
    ]
