# Generated by Django 3.2 on 2025-04-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenplays', '0009_auto_20250418_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenehighlight',
            name='certainty',
            field=models.FloatField(default=1.0, help_text='How certain the system is about this highlight (0.0 to 1.0).'),
        ),
        migrations.AddField(
            model_name='scenehighlight',
            name='conclusion',
            field=models.TextField(default='', help_text='What could be done improved'),
        ),
        migrations.AddField(
            model_name='scenehighlight',
            name='criticality',
            field=models.CharField(default='medium', help_text='How critical this highlight is (e.g., low, medium, high).', max_length=32),
        ),
    ]
