# Generated by Django 3.2 on 2025-04-19 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screenplays', '0010_auto_20250418_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified.', verbose_name='modified at')),
                ('deleted', models.BooleanField(default=False, help_text='Set to False when an element is deleted')),
                ('conflict_name', models.CharField(help_text='Short title for the conflict.', max_length=64)),
                ('introduced_at', models.CharField(help_text='Where in the story the conflict is introduced (e.g., scene number, timestamp, or description).', max_length=64)),
                ('resolved_at', models.CharField(help_text='Where in the story the conflict is resolved.', max_length=64)),
                ('description', models.TextField(help_text='General description of the conflict.')),
                ('related_text', models.TextField(help_text='The snippet of the screenplay where the conflict is evident.')),
                ('criticality', models.CharField(default='medium', help_text='How critical this conflict is to the story (e.g., low, medium, high).', max_length=32)),
                ('certainty', models.FloatField(default=1.0, help_text='How certain the system is that this is a conflict (0.0 to 1.0).')),
                ('conclusion', models.TextField(default='', help_text='How the conflict contributes to the story or could be improved.')),
                ('screenplay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_points', to='screenplays.screenplay')),
            ],
            options={
                'ordering': ['screenplay', 'introduced_at'],
            },
        ),
    ]
