# Generated by Django 3.2 on 2025-04-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenplays', '0011_conflictpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conflictpoint',
            name='conflict_name',
            field=models.TextField(help_text='Short title for the conflict.'),
        ),
        migrations.AlterField(
            model_name='conflictpoint',
            name='introduced_at',
            field=models.TextField(help_text='Where in the story the conflict is introduced (e.g., scene number, timestamp, or description).'),
        ),
        migrations.AlterField(
            model_name='conflictpoint',
            name='resolved_at',
            field=models.TextField(help_text='Where in the story the conflict is resolved.'),
        ),
    ]
