# Generated by Django 3.2 on 2025-04-19 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screenplays', '0012_auto_20250419_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conflictpoint',
            name='related_text',
        ),
    ]
