# Generated by Django 3.2 on 2025-04-19 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screenplays', '0013_remove_conflictpoint_related_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conflictpoint',
            options={'ordering': ['screenplay']},
        ),
        migrations.RenameField(
            model_name='conflictpoint',
            old_name='introduced_at',
            new_name='introduced_at_regex',
        ),
        migrations.RenameField(
            model_name='conflictpoint',
            old_name='resolved_at',
            new_name='resolved_at_regex',
        ),
    ]
