# Generated by Django 3.2 on 2025-04-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenplays', '0014_auto_20250419_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='conflictpoint',
            name='last_updated_scene_position',
            field=models.IntegerField(default=0, help_text='Conflict scene end'),
        ),
        migrations.AddField(
            model_name='conflictpoint',
            name='start_scene_position',
            field=models.IntegerField(default=0, help_text='Conflict scene start'),
        ),
    ]
