# Generated by Django 3.2 on 2025-04-21 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screenplays', '0015_auto_20250420_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified.', verbose_name='modified at')),
                ('deleted', models.BooleanField(default=False, help_text='Set to False when an element is deleted')),
                ('slugline', models.CharField(help_text="Scene heading or slugline (e.g., 'INT. HOUSE - NIGHT')", max_length=256)),
                ('content', models.TextField(help_text='Content of the scene, including action and dialogue.')),
                ('position', models.PositiveIntegerField(help_text='The order of the scene in the screenplay.')),
                ('purpose', models.TextField(blank=True, help_text='Narrative purpose of the scene (e.g., reveal character, raise stakes, foreshadowing).', null=True)),
                ('screenplay', models.ForeignKey(help_text='The screenplay this scene belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='screenplays.screenplay')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('screenplay', 'position')},
            },
        ),
    ]
