# Generated by Django 3.2 on 2025-04-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenplays', '0016_scene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='slugline',
            field=models.TextField(help_text="Scene heading or slugline (e.g., 'INT. HOUSE - NIGHT')"),
        ),
    ]
