# Generated by Django 3.2 on 2025-04-21 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screenplays', '0017_alter_scene_slugline'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scene',
            unique_together=set(),
        ),
    ]
