# Generated by Django 3.2 on 2025-04-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenplays', '0018_alter_scene_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenplay',
            name='content',
            field=models.TextField(blank=True, help_text='The full text content of the screenplay.', null=True),
        ),
    ]
