# Generated by Django 3.2 on 2025-04-21 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screenplays', '0019_alter_screenplay_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenehighlight',
            name='scene',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scene', to='screenplays.scene'),
        ),
    ]
