# Generated by Django 3.2 on 2023-06-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_externaltoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaltoken',
            name='channel',
            field=models.IntegerField(choices=[(None, '(Unknown)'), (0, 'Console'), (1, 'SMS'), (2, 'Email')], default=1),
        ),
    ]
