version: '3'

volumes:
  local_postgres_data: { }
  local_postgres_data_backups: { }

services:
  postgres:
    image: postgres:11.6

  django: &django
    build:
      context: ./
      dockerfile: ./compose/production/django/Dockerfile
    image: api
    depends_on:
      - postgres
    volumes:
      - ./api:/app
    env_file:
      - ./.envs/.prod/.django
      - ./.envs/.prod/.db
      - ./.envs/.prod/.cloud
    ports:
      - "8000:8000"
    command: /start

  redis:
    image: redis:6.2
